spring.application.name=prestamos-simulador-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/prestamos}
spring.datasource.username=${DB_USER:prestamos}
spring.datasource.password=${DB_PASSWORD:prestamos}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.locations=${FLYWAY_LOCATIONS:filesystem:../db/migrations}

simulador.cobol.executable-path=${SIMULADOR_COBOL_EXECUTABLE_PATH:/app/bin/simloan}
